ARG DOCKER_GOLANG_RELEASE=1.26-alpine
ARG DOCKER_PROMETHEUS_RELEASE=3.9.1
ARG LEAF_PROMETHEUS=http://127.0.0.1:9090
ARG LEAF_PROMETHEUS_PASS=passwd
ARG LEAF_PROMETHEUS_USER=admin
######################################################################

FROM golang:${DOCKER_GOLANG_RELEASE} AS builder
COPY . /src
WORKDIR /src
RUN go build -ldflags '-s -w' -o leaf cmd/leaf/main.go
######################################################################

FROM prom/prometheus:v$DOCKER_PROMETHEUS_RELEASE AS prometheus
######################################################################

FROM debian:stable AS runtime
LABEL app=leaf
LABEL org=osba

ENV DOCKER_GOLANG_RELEASE=$DOCKER_GOLANG_RELEASE
ENV DOCKER_PROMETHEUS_RELEASE=$DOCKER_PROMETHEUS_RELEASE
ENV LEAF_PROMETHEUS=$LEAF_PROMETHEUS
ENV LEAF_PROMETHEUS_PASS=$LEAF_PROMETHEUS_PASS
ENV LEAF_PROMETHEUS_USER=$LEAF_PROMETHEUS_USER

EXPOSE 9010/tcp
EXPOSE 9090/tcp

RUN mkdir -p /etc/leaf /etc/prometheus

COPY --from=builder /src/entrypoint.sh /.
COPY --from=builder /src/internal/config/config.yaml /etc/leaf/.
COPY --from=builder /src/leaf /bin/.

RUN sed -i "s/%%PROMETHEUS%%/${LEAF_PROMETHEUS}/g" /etc/leaf/config.yaml
RUN sed -i "s/%%PROMETHEUS_PASS%%/${LEAF_PROMETHEUS_PASS}/g" /etc/leaf/config.yaml
RUN sed -i "s/%%PROMETHEUS_USER%%/${LEAF_PROMETHEUS_USER}/g" /etc/leaf/config.yaml

COPY --from=prometheus /bin/prometheus /bin/.
COPY --from=prometheus /bin/promtool /bin/.
COPY --from=prometheus /etc/prometheus/prometheus.yml /etc/prometheus/.

RUN chmod 755 /bin/leaf

VOLUME [ "/prometheus" ]

ENTRYPOINT [ "/bin/sh", "-c"]
CMD [ "/entrypoint.sh" ]
