ARG DOCKER_GOLANG_RELEASE=1.24
ARG DOCKER_PROMETHEUS_RELEASE=3.9.1
ARG LEAF_PROMETHEUS=127.0.0.1
ARG LEAF_PROMETHEUS_PASS=passwd
ARG LEAF_PROMETHEUS_USER=admin

ENV DOCKER_GOLANG_RELEASE=$DOCKER_GOLANG_RELEASE
ENV DOCKER_PROMETHEUS_RELEASE=$DOCKER_PROMETHEUS_RELEASE
ENV LEAF_PROMETHEUS=$LEAF_PROMETHEUS
ENV LEAF_PROMETHEUS_PASS=$LEAF_PROMETHEUS_PASS
ENV LEAF_PROMETHEUS_USER=$LEAF_PROMETHEUS_USER
######################################################################

# Base container image
FROM golang:$DOCKER_GOLANG_RELEASE AS builder

# Copy code to container
COPY . /src

# Build artifact from /src
WORKDIR /src

# Update the container image and build the binary
RUN go build -ldflags '-s -w' -o leaf cmd/leaf/main.go
######################################################################

# https://github.com/prometheus/prometheus/blob/v$DOCKER_PROMETHEUS_RELEASE/Dockerfile
FROM prom/prometheus:v$DOCKER_PROMETHEUS_RELEASE AS prometheus
######################################################################

FROM debian:stable AS runtime
LABEL app=leaf
LABEL org=osba

EXPOSE 9010/tcp
EXPOSE 9090/tcp

RUN mkdir -p /etc/leaf /etc/prometheus

COPY --from=builder /src/entrypoint.sh /.
COPY --from=builder /src/internal/config/config.yaml /etc/leaf/.
COPY --from=builder /src/leaf /bin/.

COPY --from=prometheus /bin/prometheus /bin/.
COPY --from=prometheus /bin/promtool /bin/.
COPY --from=prometheus /etc/prometheus/prometheus.yml /etc/prometheus/.

RUN chmod 755 /bin/leaf

VOLUME [ "/prometheus" ]

ENTRYPOINT [ "/bin/sh" ]
CMD [ "/entrypoint.sh" ]
