---
- name: Enable and Start sleaf_cluster_stack
  systemd:
    name: "{{ sleaf_cluster_stack_service }}"
    enabled: true
    state: started
    daemon_reload: true
  listen: Enable sleaf_cluster_stack

- name: Restart sleaf_cluster_stack
  systemd:
    name: "{{ sleaf_cluster_stack_service }}"
    enabled: true
    state: restarted
    daemon_reload: true
  listen: Restart sleaf_cluster_stack
######################################################################

- name: Restart Logrotate
  systemd:
    name: logrotate.service
    enabled: true
    state: restarted
  listen: Restart Logrotate
