---
server:
  addr: "%%SERVER_ADDRESS%%:%%SERVER_PORT%%"
infrastructure:
  infra_path: "%%INFRA_CONFIG_PATH%%"
  profile_path: "%%POFILE_CONFIG_PATH%%"
prometheus:
  url: "%%PROMETHEUS%%"
  username: "%%PROMETHEUS_USER%%"
  password: "%%PROMETHEUS_PASS%%"
