---
server:
  addr: ":9010"
infrastructure:
  infra_path: "/etc/leaf/infrastructure.yaml"
  profile_path: "/etc/leaf/profile.yaml"
prometheus:
  url: "%%PROMETHEUS%%"
  username: "%%PROMETHEUS_USER%%"
  password: "%%PROMETHEUS_PASS%%"
orchestrator:
  reporting_interval: "1h"
intensity:
  ttl: "1h"
  electricity_maps:
    api_key: "5RZm8RaFVKMBfpEVpWeY"
    zone: "DE"
    base_url: "https://api.electricitymap.org"
  mix_data:
    path: "docs/electricity_mixes.csv"
    country: "DEU"