version: 1
environment:
  id: ocp-scs
  name: ScaleUp-OCP

devices:
  - id: compute01
    role: compute
    profile: compute
    rack: rack01

  - id: compute02
    role: compute
    profile: compute
    rack: rack01

  - id: compute03
    role: compute
    profile: compute
    rack: rack01

  - id: compute04
    role: compute
    profile: compute
    rack: rack01

  - id: controller01
    role: controller
    profile: controller
    rack: rack01

  - id: controller02
    role: controller
    profile: controller
    rack: rack01

  - id: controller03
    role: controller
    profile: controller
    rack: rack01

  - id: storage01
    role: storage
    profile: storage
    rack: rack01

  - id: storage02
    role: storage
    profile: storage
    rack: rack01

  - id: storage03
    role: storage
    profile: storage
    rack: rack01

  - id: manager01
    role: manager
    profile: manager
    rack: rack01

  - id: switch01
    role: network
    profile: network-switch
    rack: rack01

  - id: mgmt-switch01
    role: network
    profile: management-switch
    rack: rack01
