---
prometheus:
  url: "%%PROMETHEUS%%"
  username: "%%PROMETHEUS_USER%%"
  password: "%%PROMETHEUS_PASS%%"

metrics:
  - "kepler_node_power_watts"
  - "node_cpu_seconds_total"

infrastructure:
  hyperconverged: false
  numCompute: 3
  numNodesTotal: 10
  storage: 3
