---
leaf_bin: "/usr/local/bin/leaf"
leaf_config: "{{ leaf_user_home }}/config.yaml"
leaf_prometheus_pass: "admin"
leaf_prometheus_url: "http://127.0.0.1:9090"
leaf_prometheus_user: "admin"
leaf_repo: "https://github.com/eco-digit/leaf"
leaf_repo_branch: "main"
leaf_src_dir: "{{ leaf_user_home }}/src"
leaf_user_group: "{{ leaf_user_name }}"
leaf_user_home: "/var/lib/{{ leaf_user_name }}"
leaf_user_name: "leaf"

docker_apt_repo: "https://download.docker.com/linux/{{ansible_distribution|lower}}"
docker_apt_repo_filename: "docker"
docker_apt_repo_key: "https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg"
docker_apt_sign_key: "/etc/apt/trusted.gpg.d/{{docker_apt_repo_filename}}.asc"
docker_daemon_mtu: 1280
docker_gpg_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker_gpg_keyserver: "https://keys.openpgp.org"

os_application_credential_id: "{{ lookup('env', 'OS_APPLICATION_CREDENTIAL_ID') }}"
os_application_credential_secret: "{{ lookup('env', 'OS_APPLICATION_CREDENTIAL_SECRET') }}"
os_auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
os_auth_type: "v3applicationcredential"
os_cloud: "{{ lookup('env', 'OS_CLOUD') }}"
os_cloud_cacert_b64: ""
os_cloud_config_path: "{{leaf_user_home}}/.config/openstack/cloud.conf"
os_cloud_yaml_b64: ""
os_cloud_yaml: "{{leaf_user_home}}/.config/openstack/clouds.yaml"
os_clouds_yaml: "{{os_cloud_yaml}}"
os_control_plane_machine_flavor: "{{ os_node_machine_flavor }}"
os_control_plane_machine_image: "{{ os_image_name }}"
os_dns_nameservers: "9.9.9.9, 8.8.8.8, 1.1.1.1"
os_domain_name: "{{lookup('env', 'OS_DOMAIN_NAME') }}"
os_external_network_id: "{{ lookup('env', 'OS_EXTERNAL_NETWORK_ID') }}"
os_failure_domain: "{{lookup('env', 'OS_FAILURE_DOMAIN') }}"
os_identity_api_version: "3"
os_image_name: "Ubuntu 24.04"
os_interface: "{{ lookup('env', 'OS_INTERFACE') }}"
os_node_machine_flavor: "SCS-2V-4-20s"
os_node_machine_image: "{{os_image_name}}"
os_provider_release: "0.14.0"
os_region_name: "{{ lookup('env', 'OS_REGION_NAME') }}"
os_ssh_key_name: "mysshkey"
os_tenant_id: "{{ lookup('env', 'OS_TENANT_ID') }}"
os_worker_machine_flavor: "{{ os_node_machine_flavor }}"
os_worker_machine_image: "{{ os_image_name }}"
os_worker_machine_root_disk_size: 32
