---
leaf_bin: "/usr/local/bin/leaf"
leaf_cmd: "{{ leaf_bin }} --config {{ leaf_config }}"
leaf_config: "{{ leaf_user_home }}/config.yaml"
leaf_env_id: "leaf-env-id"
leaf_env_name: "LEAF Environment"
leaf_infra_config_path: "{{ leaf_user_home }}/infrastructure.yaml"
leaf_logfile: "{{ leaf_user_home }}/leaf.log"
leaf_logrotat_dir: "/etc/logrotate.d"
leaf_logrotate: "{{ leaf_logrotat_dir }}/leaf"
leaf_profile_config_path: "{{ leaf_user_home }}/profile.yaml"
leaf_prometheus_pass: "admin"
leaf_prometheus_url: "http://127.0.0.1:9090"
leaf_prometheus_user: "admin"
leaf_repo: "https://github.com/eco-digit/leaf"
leaf_repo_branch: "main"
leaf_server_address: "127.0.0.1"
leaf_server_port: 9010
leaf_src_dir: "{{ leaf_user_home }}/src"
leaf_systemd_unit: "/etc/systemd/system/leaf.service"
leaf_user_group: "{{ leaf_user_name }}"
leaf_user_home: "/var/lib/{{ leaf_user_name }}"
leaf_user_name: "leaf"

docker_apt_repo: "https://download.docker.com/linux/{{ansible_distribution|lower}}"
docker_apt_repo_filename: "docker"
docker_apt_repo_key: "https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg"
docker_apt_sign_key: "/etc/apt/trusted.gpg.d/{{docker_apt_repo_filename}}.asc"
docker_daemon_mtu: 1280
docker_gpg_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker_gpg_keyserver: "https://keys.openpgp.org"
