---
name: test (binary and image)

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test 'leaf' binary and Docker image
      run: make test
