---
name: test (binary and image)

on:
  push

  workflow_run:
    workflows: ["build-image"]
    types:
      - completed

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test 'leaf' binary and Docker image
      run: make test
